### ISSUE TITLE
nrm_specimens_magic not working

### ISSUE THREAD

**Issue by moonshoes87** [PmagPy/PmagPy#284]
See notebook output

**Comment by moonshoes87** [comment]
@ltauxe, does nrm_specimens_magic need to be updated to data model 3?

**Comment by moonshoes87** [comment]
Also, it isn't working right with -crd g

**Comment by ltauxe** [comment]
well, I could…  not a big deal.  I’ll give it a go.  
lisa

**Comment by moonshoes87** [comment]
I can also do it, just wasn’t sure if it had been superseded by another program.  Let me know if you want me to work on this.

**Comment by ltauxe** [comment]
it wasn’t priority.  i just did it for practice.  it now seems to work (but the output doesn’t work with eqarea_magic, so I’m not sure what is up with THAT).  anyway, i pushed something.  it shouldn’t effect you (i hope i didn’t tromp on your stuff this time - i did a merge).  

lisa

**Comment by ltauxe** [comment]
I think it works now...

**Comment by moonshoes87** [comment]
There is still a problem in nrm_specimens_magic.  dir_tilt_correction is getting populated with 'g', which is why the resulting nrm_specimens.txt doesn't plot correctly with eqarea_magic.

<img width="645" alt="screen shot 2018-01-03 at 12 39 40 pm" src="https://user-images.githubusercontent.com/1836578/34538905-2ff9489a-f083-11e7-8239-a2cd88ed2414.png">

This happens because coord == 'g' (geographic).  So, I think this line:

            NrmSpecRec['dir_tilt_correction']=coord

should be:

            NrmSpecRec['dir_tilt_correction']=orient

instead.  Is that right, @ltauxe ?

**Comment by ltauxe** [comment]
correct.  dir_tilt_correction should be -1, 0 or 100.  sorry.  
lisa
