### ISSUE TITLE
wx import failing in Jupyter notebook environment

### ISSUE THREAD

**Issue by ltauxe** [PmagPy/PmagPy#367]
works fine on the command line but fails in my notebook _PmagPy.ipynb

I cant figure out why - import wx suddenly doesn't exist but i didn't change my python environment at all.  even rebooted the computer.  weird.

**Comment by moonshoes87** [comment]
@ltauxe , this was resolved, right?

**Comment by ltauxe** [comment]
no - i followed Hanna's suggestion to reinstall wxpython for anaconda, but this did not fix it.  
the weird thing is that "import wx" works fine within a notebook code cell, and ani_depthplot works fine on the command line,  but does not work in _PmagPy.ipynb  for me: 
error is 
Traceback (most recent call last):
  File "/Users/ltauxe/Programs/PmagPy/GIT/PmagPy/programs/ani_depthplot.py", line 3, in <module>
    import wx
ImportError: No module named wx

**Comment by ltauxe** [comment]
but ipmag.ani_depthplot works great.

**Comment by moonshoes87** [comment]
that is weird.  ani_depthplot works in the notebook environment for me.  

If you run `!which python` in the notebook, is it getting Anaconda Python?  Or is some other Python somehow being grabbed?  

Also, maybe try running `!which pythonw`, since that is the environment that is being used in ani_depthplot.py.  

If nothing is working, I would try fulling uninstalling and reinstalling Anaconda Python.

**Comment by ltauxe** [comment]
it is calling the “right” python: /usr/local/bin/python.  and /usr/local/bin/pythonw   - i think this is the “right” one too

**Comment by moonshoes87** [comment]
I don’t think that is the right python — it should be something like  /Users/hermione/anaconda3/bin/python

if you’re using anaconda.

**Comment by ltauxe** [comment]
that is what /usr/local/bin/python is linked to.  
lisa

**Comment by moonshoes87** [comment]
Oh, right, I forgot that you had to do that.  This might be a problem that we should troubleshoot when I am in San Diego — it seems like something we should have documented somewhere so that others with the same problem can find out how to fix it!

**Comment by moonshoes87** [comment]
An idea for how to troubleshoot this from afar is to make a minimal script:

    print(‘about to import wx’)
    import wx
    print(‘imported wx’, wx.__file__)

or something like that.  Then we’ll know if the problem is really just the wx import, or if there is some additional context necessary to reproduce this bug.

**Comment by ltauxe** [comment]
i did try importing wx from withint the notebook…  but with the commentary, here’s what happens:

about to import wx
imported wx /Users/ltauxe/anaconda3/lib/python3.6/site-packages/wx/__init__.py

so no bug.  Then, i tried it within the _PmagPy notebook before and after importing all the other stuff with same result.  

BUT.  after this command: 

!ani_depthplot.py -f ../ani_depthplot/rmag_anisotropy.txt -fsa ../ani_depthplot/er_samples.txt \
    -fb ../ani_depthplot/magic_measurements.txt -sav -fmt png -DM 2

I get: 

Traceback (most recent call last):
  File "/Users/ltauxe/Programs/PmagPy/GIT/PmagPy/programs/ani_depthplot.py", line 3, in <module>
    import wx
ImportError: No module named wx

**Comment by moonshoes87** [comment]
Right.  I actually meant create a new script in the PmagPy/programs called minimal.py (or whatever).  Put those few lines in it, and try running that program in the notebook:

    !minimal.py

If we get the same bug as with ani_depthplot, we know it's just the wx import, but if we *don't* get that bug, then there is some other combination of factors in ani_depthplot that causes the problem.

**Comment by ltauxe** [comment]
ok.  so…  did that. works fine on command line and from within the notebook:  


also works fine.   

THEN, i wrote minimal2.py:

#!/usr/bin/env pythonw
  
print ('about to import wx')
import wx
print ('imported wx',wx.__file__)

which does this:

 so it is pythonw that is doing this.  not wx

**Comment by moonshoes87** [comment]
That’s good to know.  Maybe Anaconda is only symlinked with python, not pythonw?  So pythonw is just getting system python or something?

**Comment by moonshoes87** [comment]
Worth a try.  I don’t remember why you had to create that symlink in the first place — do you?  If that’s a problem that others are likely to run into, we should document it.

enjoy your symposium!

**Comment by ltauxe** [comment]
here’s my note to myself about this: 

if your jupyter notebook is calling the wrong python:  
do this: 

 $unlink /usr/local/bin/python

and this

$ln -s /Users/ltauxe/anaconda3/bin/python /usr/local/bin/python

so i did this same thing for pythonw and it fixed everything!!!   thanks! 

lisa
