### ISSUE TITLE
cartopy error with polemap_magic for contribution 12578

### ISSUE THREAD

**Issue by moonshoes87** [PmagPy/PmagPy#475]
**What command was run:**

```
make_magic_plots.py
```

**What happened:**
```
-I- working on pole map
polemap_magic.py -sav -fmt png -rev gv 40
-I- Using online data model
gridlines only supported for PlateCarree and Mercator plots currently
Traceback (most recent call last):
  File "/Users/nebula/Python/PmagPy/programs/polemap_magic.py", line 347, in <module>
    main()
  File "/Users/nebula/Python/PmagPy/programs/polemap_magic.py", line 224, in main
    pmagplotlib.plot_map(FIG['map'], pole_lats, pole_lons, Opts)
  File "/Users/nebula/Python/PmagPy/pmagpy/pmagplotlib.py", line 3353, in plot_map
    transform=ccrs.Geodetic(), edgecolors=Opts['edgecolor'])
  File "/Users/nebula/anaconda3/lib/python3.6/site-packages/cartopy/mpl/geoaxes.py", line 1429, in scatter
    result = matplotlib.axes.Axes.scatter(self, *args, **kwargs)
  File "/Users/nebula/anaconda3/lib/python3.6/site-packages/matplotlib/__init__.py", line 1867, in inner
    return func(ax, *args, **kwargs)
  File "/Users/nebula/anaconda3/lib/python3.6/site-packages/matplotlib/axes/_axes.py", line 4363, in scatter
    self.add_collection(collection)
  File "/Users/nebula/anaconda3/lib/python3.6/site-packages/matplotlib/axes/_base.py", line 1925, in add_collection
    self.update_datalim(collection.get_datalim(self.transData))
  File "/Users/nebula/anaconda3/lib/python3.6/site-packages/matplotlib/collections.py", line 199, in get_datalim
    offsets = transOffset.transform_non_affine(offsets)
  File "/Users/nebula/anaconda3/lib/python3.6/site-packages/matplotlib/transforms.py", line 2482, in transform_non_affine
    return self._a.transform_non_affine(points)
  File "/Users/nebula/anaconda3/lib/python3.6/site-packages/cartopy/mpl/geoaxes.py", line 137, in transform_non_affine
    xy[:, 0], xy[:, 1])[:, 0:2]
  File "lib/cartopy/_crs.pyx", line 381, in cartopy._crs.CRS.transform_points
IndexError: Out of bounds on buffer access (axis 0)
```

**Details:**

Lisa, do you want to try to fix this cartopy mapping error?

**Data file(s):**

[magic_contribution_12578.txt](https://github.com/PmagPy/PmagPy/files/2630747/magic_contribution_12578.txt)

**Screenshot(s):**

**PmagPy version:**

**Comment by ltauxe** [comment]
never mind about the -sym key, i see now what was wrong.  but I cannot reproduce this error. but I put in a test if the projection is NOT a mercator, it won't plot the grid.  this is for cartopy only.

**Comment by moonshoes87** [comment]
I am still seeing this problem.  I haven't been able to upgrade cartopy to 0.17.0, either.  Could you send me the results of `conda list`.

**Comment by ltauxe** [comment]
this is what I'm currently running: 

[conda_list_output.txt](https://github.com/PmagPy/PmagPy/files/2637390/conda_list_output.txt)

**Comment by ltauxe** [comment]
and it should work now - i put in a command that skips the gridding if the projection is not a mercator.

**Comment by moonshoes87** [comment]
@ltauxe, this is still throwing errors.  I don't think it is related to the grid, but to the transform to Geodetic in plot_map:
```
  File "/Users/nebula/Python/PmagPy/programs/polemap_magic.py", line 225, in main
    pmagplotlib.plot_map(FIG['map'], pole_lats, pole_lons, Opts)
  File "/Users/nebula/Python/PmagPy/pmagpy/pmagplotlib.py", line 3353, in plot_map
    transform=ccrs.Geodetic(), edgecolors=Opts['edgecolor'])
```

But I was able to resolve it by installing `cartopy` 0.17.0 from `conda-forge`, which it looks like you already did.  Looking at your list of packages, you must have `conda-forge` listed in your .condarc file.  That might be one of the new defaults.  (`conda-forge`  is community-run vs the default channel which is "official".)

I can change the Cookbook to use: `conda install cartopy --channel conda-forge` if we are worried about catching these edge cases until 0.17.0 is available in the main channel.

**Comment by ltauxe** [comment]
right.  I am running cartopy 0.17.0 and can’t reproduce your error.  
would you mind changing the install instructions once again?  sorry….   but hopefully that will also fix our other cartopy problems (central longitude on mollweide projection).  I’ll test that this afternoon.  
lisa

**Comment by moonshoes87** [comment]
Ok, I updated the install instructions.  I will revisit them some time safely after AGU, once cartopy 0.17.0 and matplotlib 3.0.2 are both available through the conda default channel.
